### ISSUE TITLE
minio file corruption

### ISSUE THREAD

**Issue by pppaapp** [eikek/sharry#1039]
I uploaded a file to minio and downloaded it.

The file was corrupted and I couldn't open it.

Is there a problem with minio?

**Comment by eikek** [comment]
I didn't know that there is a problem. Last time I tried, it worked for me. Can you share any more details so I could try to reproduce it?

**Comment by eikek** [comment]
Ok, I'll try it out when I have some spare time.

**Comment by VNuserX** [comment]
No, minio in distributed mode (HA), used pretty widely in our infrastructure
Also just for test , set up using filesystem - problem gone
Thanks in advance

**Comment by devplayer0** [comment]
I seem to be encountering this issue too :(

**Comment by eikek** [comment]
Hi there, finally got around to have a look, sorry for the delay. It turns out that this is something I fixed quite a while ago (https://github.com/eikek/binny/pull/225) but didn't publish a release for sharry :(. Good news is that the data gets only mangled on the way down. So in minio the dtata is fine. Using the current nightly version should be working in your cases - would be nice if you could give it a try if that is possible, just to get it confirmed from someone else :). I'll do a release soon.

**Comment by VNuserX** [comment]
Hi, thanks for replay, it work indeed, but "nightly" version failed to start with 

" - (reference.conf @ jar:file:/opt/sharry-restserver-1.13.0-SNAPSHOT/lib/com.github.eikek.sharry-restserver-1.13.0-SNAPSHOT.jar!/reference.conf: 261) Key not found: 'scope'."

Basically force to add oauth section in config, and required all keys
```
      oauth = [
          {
             enabled = false
             id = "github"
             name = "Github"
             icon = "fab fa-github"
             authorize-url = "https://github.com/login/oauth/authorize"
             token-url = "https://github.com/login/oauth/access_token"
             user-url = "https://api.github.com/user"
             user-id-key = "login"
             scope = ""
             client-id = "<your client id>"
             client-secret = "<your client secret>"
           }
      ]
```

**Comment by VNuserX** [comment]
you are welcome, waiting for release (:
