### ISSUE TITLE
unable to open Sharry

### ISSUE THREAD

**Issue by pluisenbol** [eikek/sharry#222]
When I open sharry it just kicks me out for some reason 

[video](https://youtu.be/iwEbG_PAXyM)

**Comment by Luca-Castelnuovo** [comment]
I don't really know how this system functions so I can't give you specific tips but,

1. Have you tried in icognito mode or cleared your site data?
2. Have you checked the application/webserver logs?

**Comment by eikek** [comment]
That is strange indeed. The tips are good, thank you @Luca-Castelnuovo. I'm curious what the logs say and if it can be reproduced in incognito mode. Another thing to look at would be the network and console tab in the browser's dev tools (its `F-12` in firefox).

**Comment by pluisenbol** [comment]
It had indeed something to do with the site data I tried to load the site from another browser and then it did work. So I cleared everything with CCleaner and then everything worked again

**Comment by eikek** [comment]
Ah that's nice to hear. I'm still wondering what caused this, because it seems to be something that could be fixed in sharry. If you have some infos for me to reproduce it, I'd like to know. Otherwise I tend to close this issue, because there is nothing to do about it right now. If it comes up again, it can be reopened or a new issue is fine.

**Comment by pluisenbol** [comment]
I also have no idea what caused this so reproducing it will be hard. I will close the issue when I figure out how to do that.
