### ISSUE TITLE
feature request: better pg_snakeoil integration

### ISSUE THREAD

**Issue by fstcapb** [eikek/sharry#255]
Hi eikek,

thank you very much for the great software and awesome support so far. 

I use sharry in combination with pg_snakeoil, a virus detection in postgres https://github.com/credativ/pg_snakeoil

Currently the upload of eicar virus files starts several times, stops with an error message to the uploader and a 0kb file is shown in the share. This works, but it would be great to have a better information about the virus infected upload for uploader (and receiver).

One could include pg_snakeoil into sharry very easily by:
- install pg_snakeoil - e.g. on ubuntu systems package: postgresql-12-snakeoil
- execute the following sql commands on the sharry postgres database:
  CREATE EXTENSION pg_snakeoil;
  create domain public.safe_bytea as bytea check (not so_is_infected(value));
  ALTER TABLE public.filechunk ALTER COLUMN chunkdata TYPE safe_bytea;

Virus Test Files can be found here:
https://www.eicar.org/?page_id=3950

Best regards,
Falk

**Comment by eikek** [comment]
Hi Falk,

that's great! Thanks a lot for the pointer, I didn't know about snakeoil. I definitely like to support this. The only difficulty is to not break things for mariadb and h2 and I think it should be optional, as it might be difficult to install on some systems.

So (I didn't read all the info on your links yet): as I understand, snakeoil removes the chunks with viruses when changing the type to `safe_bytea`? If it's only this SQL statements, that should be easy to add. What else would be needed – I think showing a better error messages in the UI. How can this info be retrieved? Or maybe it would be possible to have a trigger (or something, I'm not a db expert) that inserts a "info.txt" file containing the text "your upload was removed due to viruses"? This way a code change could be avoided (since it's only postgres).

Thanks and kind regards
Eike

**Comment by fstcapb** [comment]
Hi Eike, 

im sorry for the delay. 

the snakeoil extension offers functions to update the virus database, do a virus check or get the virus name of an infected file. The command  "create domain public.safe_bytea as bytea check (not so_is_infected(value));" creates the datatype safe_bytea that can be used like bytea, but throws exceptions when a virus is detected. 
I think the update virus database command can be ignored, because it's usually done by a cron job (every hour).

Here is an example with type text, but it works same:
CREATE EXTENSION pg_snakeoil;
CREATE DOMAIN safe_text AS text CHECK (NOT so_is_infected(value));
CREATE TABLE t1(safe safe_text);

INSERT INTO t1 VALUES ('This text is safe!');
INSERT

INSERT INTO t1 VALUES('X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*');
NOTICE:  Virus found: Eicar-Test-Signature
ERROR:  value for domain safe_text violates check constraint "safe_text_check"

so, the alter table command modifies the insert to not only do an insert but also do a virus check before. If a virus gets detected the insert command throws an error and the insert does not happen. 

I think the exception of the insert command is good to create the error messages for the users - maybe with a try catch or something comparable. I imagine the catch phrase could be designed in a way that only fits to that snakeoil error message. What do you think?

Best regards,
Falk

**Comment by eikek** [comment]
Hi Falk, no need to apologize! There is time for this when there is time :)

This sounds reasonable; I have to play with it. Not sure if the "NOTICE" message gets through jdbc into the app.

Do you think sharry should run the `CREATE EXTENSION` commands as part of its DB migration? Currently it's all static, for this I need to detect, whether this extension is available (or ignore errors). This is a one-time thing,right? A second approach would be to document the steps somewhere maybe?

**Comment by fstcapb** [comment]
I think using snakeoil should be optional. I don't know how snakeoil works with docker. On other installations an admin has to choose to install the postgres extension (e.g. Package postgresql-12-snakeoil on Ubuntu Systems). So I think in that case, the decision to use snakeoil is made, when the extension is available. 

I think you could check for the availability of the extension in the sharry code with an SQL command (SELECT * FROM pg_available_extensions WHERE name = 'pg_snakeoil' ) and execute the SQL commands for the use of snakeoil depending on that result. Of cause you could also ignore that commands and document them somewhere. In that case the only thing to change would be to show the virus information to sender and receiver. 

The snakeoil SQL commands need to be executed only once. But one could install sharry and postgres first, do some uploads and install the snakeoil extension later. The alter table command causes an error, if the table contains virus data.

**Comment by eikek** [comment]
ftr, I finally tested it myself, thanks for your steps! The notice message seems not to be transported to the app, so I think I need to inspect the other error message. I think I will leave it to add the extension manually, since it's not that hard and only required once. This is a bit fragile, but should work ok if people follow the create-extension steps closely.

**Comment by eikek** [comment]
Hi Falk,

so what I did now is this:

- people must install the extension and the domain manually as you described (it is so simple and only necessary once)
- sharry allows to configure a mapping from database "native" error messages into those that should be shown to a user
- sharry then inspects the error message from the database, does a simple substring check and if that matches one of the configured strings, it sends out a 422 response with the translated message. 
- The ui stops retrying on a 422 and shows the message

So this allows to add other checks, too, or when mysql may have a similar thing but a slightly different error message.

There is one caveat: it is necessary to install the extension *after* sharry has created the database, otherwise it gets confused about a non-empty schema that it wants to "own" regarding migration scripts.
