### ISSUE TITLE
After the instance restarts, the shared files disappear?

### ISSUE THREAD

**Issue by CicoZhang** [eikek/sharry#345]
Hi, 
So grateful to have this setup making file sharing easier.
I am running it on a Raspberry server, installing it via deb file. 
After the instance restarts, all the files uploaded in the previous instance disappear, is that normal? Is there a fix (files are still somewhere?)

Thanks.

**Comment by eikek** [comment]
Hi @CicoZhang , thank you! Well, this is not normal of course. The files should be kept in the database and if they are still there, they should be visible in the app…. I'm not sure what the reason is. Can you give some more details? What db are you using? Are there any errors in the logs when restarting? you can also paste the logs from first and second run… maybe I spot something there…

**Comment by eikek** [comment]
Hi @CicoZhang let me know if I can help you with anything here. I'm closing this for now, but feel free to re-open or create new issues.

**Comment by sakshamchawla** [comment]
Seeing didn't have any follow-up, I'm facing the same issue. 

Deployment details: 
Ubuntu 20.04 LTS on GCP Compute Engine

Here's part of my config for storage
```
files {
      default-store = "filesystem"
      stores = {
        database =
          { enabled = false
            type = "default-database"
          }

        filesystem =
          { enabled = true
            type = "file-system"
            directory = "/home/user/sharry-data"
            clean-empty-dirs = true
          }

        minio =
          { enabled = false
            type = "s3"
            endpoint = "http://localhost:9000"
            access-key = "username"
            secret-key = "password"
            bucket = "sharry"
          }
      }
```
Whenever I restart the instance, Sharry doesn't list the shares or the aliases. The data is still there in `~/sharry-data`, but it doesn't seem to read it. Create a new alias the original ID doesn't list the older shares under that alias either. However, this happens when the system is rebooted, it doesn't happen the the service itself is restarted. Any thoughts?

**Comment by sakshamchawla** [comment]
```
   jdbc {
      url = "jdbc:h2://"${java.io.tmpdir}"/sharry-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
      user = "sa"
      password = ""
    }
```

I'm on the default jdbc config. However, the config is set to use filesystem for storage. 
>  It could be that the directory is cleared on reboots on some systems.
Not sure about that, the directory still lists the data (in the chunk format) after reboot

**Comment by eikek** [comment]
> > It could be that the directory is cleared on reboots on some systems.
> 
> Not sure about that, the directory still lists the data (in the chunk format) after reboot

Perhaps a misunderstanding - the chunk format is about the files itself. But the database is needed to maintain everything else (it can also store the files, but I think you chose to use the filesystem for that). By default it is written to `"${java.io.tmpdir}"/sharry-demo.db` (and `java.io.tmpdir` is usually `/tmp` on linux systems). This directory must be changed or use postgres for example.

**Comment by sakshamchawla** [comment]
Ah. that clears it up. I didn't realize except for that data itself, everything else is stored in the database with my configuration. Thank you!
