### ISSUE TITLE
[FEATURE] Enable SSL for HTTPS

### ISSUE THREAD

**Issue by DarrenAlex** [eikek/sharry#413]

**Comment by eikek** [comment]
I use a nginx in front to terminate all my ssl connections. Do you think it is necessary to provide ssl support right from the app?

**Comment by DarrenAlex** [comment]
IMO, yes. Shouldn't be that hard

**Comment by DarrenAlex** [comment]
After reading the documentation I think it's possible to use built-in features (Nginx reverse proxy) but the documentation isn't clear. Mind clearing up the documentation?

**Comment by eikek** [comment]
Hi @DarrenAlex I think I don't understand, sorry. I don't think it is currently possible without a reverse proxy. But you can use nginx for example (I'm using nginx and Let'sEncrypt for tls across all projects, but there are others). Then I'd recommend nginx documentation, [this](https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/) seems quite good. I can't provide instructions for all systems/os. Only for these that I'm using, which is maybe not what you are using. 

If you know how to improve the docs, I gladly accept pull requests :-). Or can you be more specific on what needs clearing?

**Comment by DarrenAlex** [comment]
Hi @eikek I think I have an idea. As I don't know how to set up SSL in the first place, forgive me if I'm wrong.

As highlighted [here](https://eikek.github.io/sharry/doc/reverseproxy#Nginx), I think it is possible to make a guide. As far as I know, all I need to do is to change the config file outlined there. However it would be better if some fields are highlighted and explained for clarity.

I might be able to make a PR, mind sharing your instructions so I can adapt them to suit most operating systems?

**Comment by eikek** [comment]
>  As I don't know how to set up SSL in the first place, forgive me if I'm wrong.

No worries; it's not very hard in general, but there are sometimes some subtleties to it. It is usually best to just use the defaults and only specify your certificate+key, imho. I think let's encrypt made the whole process around it a lot easier.


> I might be able to make a PR, mind sharing your instructions so I can adapt them to suit most operating systems?

The config section on the page you linked to already contains examples for how to specify the ssl certificates (see `ssl_certificate` and related settings). This is actually my config file, almost verbatim. You need to change server_name and paths to files etc. I think we could put a link to the nginx documentation site, because this is always up-to-date. It is imho a bit out of scope to explain how to configure nginx at sharry docs - there are so many tutorials/documentation sites available for this. 

Are there any specific things you need to know/have problems with?

**Comment by DarrenAlex** [comment]
> I think we could put a link to the nginx documentation site, because this is always up-to-date.
I agree, we could put a link there for clarity. The only thing that might be confusing for people is where the config file is located (and the filename of the config file) as there are multiple config files for each installation of Nginx.
We should also put a link to Let's Encrypt's website to get the certificates.

**Comment by eikek** [comment]
Yeah, I think it is good to add some links as pointers. Where the config files are located is also different on each system. You can always create a single config file and run `nginx -c /path/to/config` - but this is not a good advice in general, because distros have prepared these files usually. Then others run it via docker for example, there it's again different. I think one should use the documentation of the respective OS/system in use (I think the debian man page of nginx mentions the location of the config file, the docker nginx image has its own documentation, too).

**Comment by DarrenAlex** [comment]
I see. What I meant was the name of the file and the location, such as `sites-enabled/default.conf` or `/nginx.conf`.

**Comment by eikek** [comment]
> such as `sites-enabled/default.conf` or `/nginx.conf`.

Yes, this is specific to your distribution. In general, nginx doesn't care about the naming of the file. But distros have their ways, but these differ. Sometimes you add a file to `sites-available` and symlink it to `sites-enabled`. I don't want to add information for one… after all people need to consult the documentation of their respective system. Sharry is not the right place to look for how to configure nginx in general.

**Comment by eikek** [comment]
Having said all this, if you like to improve the docs here, feel free to submit a PR! I'd clearly mention that these are examples to help get started. Having some pointers to nginx/letsencrypt sites would really help. But it's not a how-to or a guide for nginx in general. There are so many already only a few searches away.

**Comment by DarrenAlex** [comment]
I see. Will work on it once I figure it out. If I have some free time, I might be able to include SSL in a release. Thanks for the help!

**Comment by DarrenAlex** [comment]
While we're at it, how easy would it be to restrict OAuth login to a particular domain?

**Comment by eikek** [comment]
> While we're at it, how easy would it be to restrict OAuth login to a particular domain?

Not sure what you mean - currently you can configure where you want to authenticate, for example at github or google or something else. But I guess this is not what you have in mind? Sorry if I miss the obvious.

**Comment by DarrenAlex** [comment]
Ah, sorry for the misunderstanding. Worded it strangely.
What I meant was to restrict signups/logins to a certain G Suite domain, such as `alice@yourdomain.tld`.
So if it was configured to only accept Google logins from `yourdomain1.tld` and `alice@yourdomain.tld` tried to login/signup, she would be disallowed.
I think it can only be applied to Google.

**Comment by eikek** [comment]
I'm not sure what you mean with callback-url? (I'm not very much familiar with the complete oauth expert :-S)

Sharry uses the "code flow" and is delegating authentication to some provider, which then redirects back to sharry. So there is a redirect-url. When the redirect url is invoked, sharry tries to obtain a token and then uses the configured user-url to get an email or user id or something to use as an account name. Sharry doesn't check anything here.

I think deciding who may login or not is part of the provider, because it is responsible for the authentication. I don't know the google tools, though. I could imagine that you might be able configure the client app/client secret within a specific domain/g-suite?

**Comment by eikek** [comment]
Hi @DarrenAlex I added some link to the nginx docs. If you think it is enough like this, we can close this. Otherwise let me know what cen be improved or just improve it :-).

**Comment by eikek** [comment]
Closing this; feel free to reopen should there be more to do.
