### ISSUE TITLE
Installation on Synology Docker

### ISSUE THREAD

**Issue by andreastanner** [eikek/sharry#520]
Hi 

I was just trying to install sharry on my synology docker but i couldn't figure out in the quickstart guide where to point the folders on the NAS to the Mount Path of the container. Can you help me here?

Thanks a lot!

**Comment by eikek** [comment]
Hi @andreastanner I'm afraid I can't help you with synology specifically, because I don't use it. But sharry needs a database. if you don't use postgres or mariadb, you can use h2 which requires a writeable directory. So you need to make a folder available to sharry to write into it. And this folder must be specified in the sharry config file in the jdbc url.

Maybe there are some users that use Synology who read this and could provide better tips here.

**Comment by filcuk** [comment]
Hi @andreastanner, you'll want to do something like this:
```
volumes:
      - /volume1/docker/appdata/sharry/sharry.conf:/opt/sharry.conf
```
If you're spinning this up from the docker app rather than compose or cli, make sure to include the command `/opt/sharry.conf`
