### ISSUE TITLE
[DOCKER] [UNRAID] Can't login after first launch

### ISSUE THREAD

**Issue by SmartPhoneLover** [eikek/sharry#655]
Hello,

I have installed Sharry following appropiate steps to configure it to comunicate with an external MariaDB database. But, after building anf starting the container, it fails to load its page.

**This my configuration:**
Docker command (removed unnecessary parts):
```
docker create --name='Sharry' --net='bridge' -p '9090:9090/tcp' -v '/mnt/user/appdata/sharry/config/sharry.conf':'/opt/sharry.conf':'ro' 'eikek0/sharry'
```

**/opt/sharry.conf:**
The DB configuration is correct, as it's working on that port (3307) on my host:
<https://pastebin.com/cvrfWA8z>

**This is the log:**
<https://pastebin.com/ea2UUFbd>

Thank you.

**Comment by eikek** [comment]
Hi @SmartPhoneLover ,

the problem is, that sharry is not picking up your config file. In the logs you see what config values are active:
```
***> v1.9.0 (#0e8cc113)
***> Base-Url: http://localhost:9090
***> Database: jdbc:h2:///tmp/sharry-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
***> Config: /opt/sharry-restserver-1.9.0/bin/../conf/sharry.conf
```
You mounted the file inside the container, but you also need to pass it as an argument. Sharry doesn't assume anything about its environment, you need to tell it. You can also look into the docker compose file. I think you only need to add it to your command:

```
docker create --name='Sharry' \
  --net='bridge' \
  -p '9090:9090/tcp' \
  -v '/mnt/user/appdata/sharry/config/sharry.conf':'/opt/sharry.conf':'ro' \
  'eikek0/sharry' /opt/sharry.conf
```

As far as I know, everything after the image name is passed as an argument to the command specified in the image.

**Comment by SmartPhoneLover** [comment]
After adding the argument you mentioned, it started successfully.

Thank you very much.

**Comment by eikek** [comment]
Great! You're welcome
