### ISSUE TITLE
Request: OAuth accounts follow signup mode

### ISSUE THREAD

**Issue by malton33** [eikek/sharry#676]
I am using a setup that uses OAuth only for accounts, and I have gotten it to work so far. But, one thing that is a problem is that anyone can make an account if they sign in through OAuth, regardless of my signup setting. So, could it be possible for accounts made through OAuth to have to abide by the signup mode? Thanks in advance.

**Comment by eikek** [comment]
Hi @malton33 - I'm not sure if I understand: is it that users authenticated via oauth are allowed to create accounts?

**Comment by malton33** [comment]
Yes, that's correct, even if I have my signups mode set to invite or closed.

**Comment by eikek** [comment]
Thank you! This is a bug then. These users should not be able to create accounts - only admins are.

**Comment by malton33** [comment]
Sorry, I think that there is a misunderstanding. My issue is not that OAuth users can create other accounts, it's that an account is automatically created for them when they sign in, regardless of my signup mode setting.

**Comment by eikek** [comment]
Ah I see. This is intentional. The signup setting is a different thing, independent from oauth. Basically, when using oauth, sharry leaves account management to you and your oauth provider, where this can be controlled. For example, you can use a `user-id-key` that is only available for the accounts you want to be able to login. Some providers (for example keycloak) also allow to control signup. For cases where you don't have enough control, there is internal account management provided.

**Comment by malton33** [comment]
Thank you for the clarification.
