### ISSUE TITLE
Modification of the login page and HTTPS

### ISSUE THREAD

**Issue by mr-biggles** [eikek/sharry#838]
Hello, I just installed Sharry with the docker container.

 ̶I̶ ̶w̶o̶u̶l̶d̶ ̶l̶i̶k̶e̶ ̶t̶o̶ ̶r̶e̶m̶o̶v̶e̶ ̶t̶h̶e̶ ̶"̶S̶i̶g̶n̶ ̶U̶P̶"̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶l̶o̶g̶i̶n̶ ̶p̶a̶g̶e̶ ̶t̶o̶ ̶a̶v̶o̶i̶d̶ ̶t̶h̶e̶ ̶a̶c̶c̶o̶u̶n̶t̶ ̶c̶r̶e̶a̶t̶i̶o̶n̶.̶ (Edit :I found the line to modify)

I would like to access the site via HTTPS with port 443 with a certificate

Do you know if my request is feasible, if so do you have the steps to follow please?

**Comment by eikek** [comment]
Using https is out of scope for sharry, because usually people use a reverse proxy for this that also manages all other apps. I'm using nginx, for example, but there are many others. You also need a valid certificate, of course. There are many resources on the internet on this. I think a good and relatively easy approach is [let's encrypt](https://letsencrypt.org/) - they have good docs and a help forum.

**Comment by mr-biggles** [comment]
Thanks for your feedback, I just saw the reverse proxy with Nginx, I will look into it and set it up.

Thanks again :)
