### ISSUE TITLE
sqlite support, view files on filesystem

### ISSUE THREAD

**Issue by electrofloat** [eikek/sharry#974]
Hi!

I'm trying this one out and have a couple of questions. 
I can see that there were some pull request for sqlite jdbc, for ex.: https://github.com/eikek/sharry/pull/147
but sqlite is not mentioned in the docs, and using it, it fails to start:
```
2023.02.07 13:13:02:0003 [io-comp...] [ERROR] com.zaxxer.hikari.HikariConfig - Failed to load driver class org.sqlite.JDBC from HikariConfig class classloader jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc
java.lang.RuntimeException: Failed to load driver class org.sqlite.JDBC in either of HikariConfig class loader or Thread context classloader
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:491)
```

1. So is sqlite3 supported or not?

2. Does it need a database at all, when default store = filesystem?
3. Is there a way to view/get the files as is when the store is filesystem and not as some blobs?

Thanks.

**Comment by eikek** [comment]
Hi @electrofloat ,

1. sqlite3 is not supported. But you can use [H2](https://h2database.com), which is very similar. It is also a file-based sql database running embedded in the process (no external server needed). I can't quite remember, but probably very early, I tried to support sqlite, but it is gone since quite some time.
2. Yes a database is required. It is used to store user account data and relations to share and files, expiration dates etc.
3. You can view the files in the filesystem, but I'm afraid it is not "human readable". It will be stored in chunks where each chunk is a single file. But using `cat` you can quickly concatenate all into the final file if you want.

kind regards
