### ISSUE TITLE
Views for password-protected shares are counted twice

### ISSUE THREAD

**Issue by 1nv** [eikek/sharry#991]
STR

1. Create a new share with "Maximum Public Views" set to "3" and any non-empty password.
2. Publish the share and go to its Details. Note that the Views counter shows "0".
3. Open the share link in a separate browser tab, it will prompt you to enter password. Note that the Views counter is still at "0".
4. Enter the password, this will grant you access to the share. Note the Views counter value.

Expected Result: Views counter shows "1".
Actual Result: Views counter shows "2". The counter seems to increase by 2 with each view.

5. Refresh the page on the separate browser tab.

Actual Result: This will show some weird page with 'The requested resource doesn't exist.' error, yet the file will still be available below.

Tested on Nightly build: https://github.com/eikek/sharry/commit/3625ea3cf1290db6fa6478cb0d653bf1407f5b35

BTW, big thanks for a great application! It seems to solve the exact problem with file sharing I've been struggling with recently!

**Comment by eikek** [comment]
Thanks again for the good report! Interesting that this could go unnoticed for so long :)

**Comment by eikek** [comment]
> Actual Result: This will show some weird page with 'The requested resource doesn't exist.' error, yet the file will still be available below.

I fixed the wrong counting, but unfortunately I couldn't reproduce this bug. But I'm suspecting that this is happening non-deterministic based on how the browser times the two requests that are send almost at the same time. If one returns successful, because the counter was just one before max, then the result will be file list will be rendered. So it could be that it receives the response of the "first" request _after_ the response of the "second" second request.
